import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-[#111111] md:h-screen text-white`}>
        <Navbar />
        <div className="max-w-[1300px] mx-auto px-5 md:h-[calc(100vh-60px)]">
          {children}
        </div>
      </body>
    </html>
  );
}
